// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user.proto

package pb_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v3/api"
	client "github.com/micro/go-micro/v3/client"
	server "github.com/micro/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for LoginService service

func NewLoginServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for LoginService service

type LoginService interface {
	Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error)
}

type loginService struct {
	c    client.Client
	name string
}

func NewLoginService(name string, c client.Client) LoginService {
	return &loginService{
		c:    c,
		name: name,
	}
}

func (c *loginService) Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error) {
	req := c.c.NewRequest(c.name, "LoginService.Login", in)
	out := new(LoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LoginService service

type LoginServiceHandler interface {
	Login(context.Context, *LoginRequest, *LoginResponse) error
}

func RegisterLoginServiceHandler(s server.Server, hdlr LoginServiceHandler, opts ...server.HandlerOption) error {
	type loginService interface {
		Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error
	}
	type LoginService struct {
		loginService
	}
	h := &loginServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&LoginService{h}, opts...))
}

type loginServiceHandler struct {
	LoginServiceHandler
}

func (h *loginServiceHandler) Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error {
	return h.LoginServiceHandler.Login(ctx, in, out)
}

// Api Endpoints for RegisterService service

func NewRegisterServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for RegisterService service

type RegisterService interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error)
}

type registerService struct {
	c    client.Client
	name string
}

func NewRegisterService(name string, c client.Client) RegisterService {
	return &registerService{
		c:    c,
		name: name,
	}
}

func (c *registerService) Register(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error) {
	req := c.c.NewRequest(c.name, "RegisterService.Register", in)
	out := new(RegisterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RegisterService service

type RegisterServiceHandler interface {
	Register(context.Context, *RegisterRequest, *RegisterResponse) error
}

func RegisterRegisterServiceHandler(s server.Server, hdlr RegisterServiceHandler, opts ...server.HandlerOption) error {
	type registerService interface {
		Register(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error
	}
	type RegisterService struct {
		registerService
	}
	h := &registerServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&RegisterService{h}, opts...))
}

type registerServiceHandler struct {
	RegisterServiceHandler
}

func (h *registerServiceHandler) Register(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error {
	return h.RegisterServiceHandler.Register(ctx, in, out)
}
